[project]
name = "tomori_data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.10",
    "crawl4ai>=0.3.5",
    "logging>=0.4.9.6",
]
